//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TRAMADE.Properties {
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;
        internal Resources() {}
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    resourceMan = new global::System.Resources.ResourceManager("TRAMADE.Properties.Resources", typeof(Resources).Assembly);
                }
                return resourceMan;
            }
        }
        internal static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }
        internal static System.Drawing.Bitmap MAS { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("MAS", resourceCulture))); } }
        internal static System.Drawing.Bitmap ACTUALIZAR { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("ACTUALIZAR", resourceCulture))); } }
        internal static System.Drawing.Bitmap SEGUIMIENTO { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("SEGUIMIENTO", resourceCulture))); } }
        internal static System.Drawing.Bitmap totalproductos { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("totalproductos", resourceCulture))); } }
        internal static System.Drawing.Bitmap Inventario { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Inventario", resourceCulture))); } }
        internal static System.Drawing.Bitmap USUARIO { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("USUARIO", resourceCulture))); } }
        internal static System.Drawing.Bitmap inventario { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("inventario", resourceCulture))); } }
        internal static System.Drawing.Bitmap Compras { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Compras", resourceCulture))); } }
        internal static System.Drawing.Bitmap Ventas { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Ventas", resourceCulture))); } }
        internal static System.Drawing.Bitmap Proveedores { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Proveedores", resourceCulture))); } }
        internal static System.Drawing.Bitmap Usuario { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Usuario", resourceCulture))); } }
        internal static System.Drawing.Bitmap Productosagotados { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Productosagotados", resourceCulture))); } }
        internal static System.Drawing.Bitmap Cerrar { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Cerrar", resourceCulture))); } }
        internal static System.Drawing.Bitmap Home { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Home", resourceCulture))); } }
        internal static System.Drawing.Bitmap Logo_de_la_empresa { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Logo de la empresa", resourceCulture))); } }
        internal static System.Drawing.Bitmap comprasrealizadas { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("comprasrealizadas", resourceCulture))); } }
        internal static System.Drawing.Bitmap Menu { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Menu", resourceCulture))); } }
        internal static System.Drawing.Bitmap Menu1 { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Menu1", resourceCulture))); } }
        internal static System.Drawing.Bitmap vistaClientes2 { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("vistaClientes2", resourceCulture))); } }
        internal static System.Drawing.Bitmap TIEMPO { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("TIEMPO", resourceCulture))); } }
        internal static System.Drawing.Bitmap GESTION { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("GESTION", resourceCulture))); } }
        internal static System.Drawing.Bitmap GESTION1 { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("GESTION1", resourceCulture))); } }
        internal static System.Drawing.Bitmap COMPRAS { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("COMPRAS", resourceCulture))); } }
        internal static System.Drawing.Bitmap MAS1 { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("MAS1", resourceCulture))); } }
        internal static System.Drawing.Bitmap DINERO { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("DINERO", resourceCulture))); } }
        internal static System.Drawing.Bitmap GES { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("GES", resourceCulture))); } }
        internal static System.Drawing.Bitmap Maximizar { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Maximizar", resourceCulture))); } }
        internal static System.Drawing.Bitmap Minimizar { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Minimizar", resourceCulture))); } }
        internal static System.Drawing.Bitmap Clientes1 { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Clientes1", resourceCulture))); } }
        internal static System.Drawing.Bitmap Reportes { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Reportes", resourceCulture))); } }
        internal static System.Drawing.Bitmap ventasrealizadas { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("ventasrealizadas", resourceCulture))); } }
        internal static System.Drawing.Bitmap Clientes { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Clientes", resourceCulture))); } }
        internal static System.Drawing.Bitmap vistaClientes { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("vistaClientes", resourceCulture))); } }
    }
}
